# Generated by Django 4.1.3 on 2023-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Portuguese'), ('en-US', 'English'), ('es-ES', 'Spanish')], max_length=5),
        ),
    ]
