# Generated by Django 4.1.3 on 2023-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Portuguese (Brazil)'), ('en-US', 'English (United States)'), ('es-ES', 'Spanish (Spain)')], max_length=5),
        ),
    ]
